<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro">  

  <xacro:macro name="barrel" params="prefix parent dir">
    <joint name="${prefix}_joint" type="continuous">
      <parent link="${parent}"/>
      <child link="${prefix}_link"/>
      <origin rpy="${pi/2} 0 ${dir}" xyz="${0.014*cos(dir)} ${0.014*sin(dir)} 0.006"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0.001"/>
    </joint>
    <link name="${prefix}_link">
      <visual>
        <geometry>
          <mesh filename="package://s4_description/stl/barrel.stl" />
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://s4_description/stl/barrel.stl" />
        </geometry>
      </collision>
      <inertial>
        <mass value="0.002"/>
        <inertia ixx="0.000001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.000001"/>
      </inertial>  
    </link>
    <transmission name="${prefix}_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}_joint">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="${prefix}_motor">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
    <gazebo reference="${prefix}_link">
      <mu1 value="2.5" />
      <mu2 value="2.5" />
      <kp value="1000" />
      <kd value="10" />
      <material>Gazebo/Black</material>
    </gazebo>
    
    <joint name="${prefix}_mark_joint" type="fixed">
      <parent link="${prefix}_link"/>
      <child link="${prefix}_mark_link"/>
      <origin rpy="0 0 0" xyz="0.005 0 0"/>
    </joint>
    <link name="${prefix}_mark_link">
      <visual>
        <geometry>
          <box size="0.005 0.005 0.005"/>
        </geometry>
        <material name="white"/>
      </visual>
    </link>
    <gazebo reference="${prefix}_mark_link">
      <material>Gazebo/White</material>
    </gazebo>
  </xacro:macro>

  <xacro:macro name="omni_wheel" params="prefix parent radius dir height">
    <joint name="${prefix}/motor_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="${prefix}/motor_link"/>
      <origin rpy="0 0 ${dir}" xyz="${radius*cos(dir)} ${radius*sin(dir)} ${height}"/>
    </joint>
    <link name="${prefix}/motor_link">
      <visual>
        <geometry>
          <mesh filename="package://s4_description/stl/motor.stl" />
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <material name="gray"/>
      </visual>
      <inertial>
        <mass value="0.180"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
      </inertial>
      <collision>
        <geometry>
          <mesh filename="package://s4_description/stl/motor.stl" />
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}/wheel_joint" type="continuous">
      <parent link="${prefix}/motor_link"/>
      <child link="${prefix}/wheel_link"/>
      <origin rpy="0 ${radians(90)} 0" xyz="0.0227 0 0"/>
      <axis xyz="0 0 1"/>
      <limit velocity="12.0" effort="1.0" />
      <dynamics damping="0.1"/>
    </joint> 
    <link name="${prefix}/wheel_link">
      <inertial>
        <mass value="0.025"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
      </inertial>  
      <visual>
        <geometry>
          <mesh filename="package://s4_description/stl/wheel.stl" />
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <material name="gray"/>
      </visual>
    </link>

    <joint name="${prefix}/wheel_s_joint" type="fixed">
      <parent link="${prefix}/wheel_link"/>
      <child link="${prefix}/wheel_s_link"/>
      <origin rpy="0 ${pi} ${pi/4}" xyz="0 0 0"/>
    </joint>
    <link name="${prefix}/wheel_s_link">
      <inertial>
        <mass value="0.025"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
      </inertial>  
    </link>
    <xacro:barrel prefix="${prefix}/barrel_1" parent="${prefix}/wheel_link" dir="0"/>
    <xacro:barrel prefix="${prefix}/barrel_2" parent="${prefix}/wheel_link" dir="${pi/2}"/>
    <xacro:barrel prefix="${prefix}/barrel_3" parent="${prefix}/wheel_link" dir="${pi}"/>
    <xacro:barrel prefix="${prefix}/barrel_4" parent="${prefix}/wheel_link" dir="${-pi/2}"/>

    <xacro:barrel prefix="${prefix}/barrel_5" parent="${prefix}/wheel_s_link" dir="0"/>
    <xacro:barrel prefix="${prefix}/barrel_6" parent="${prefix}/wheel_s_link" dir="${pi/2}"/>
    <xacro:barrel prefix="${prefix}/barrel_7" parent="${prefix}/wheel_s_link" dir="${pi}"/>
    <xacro:barrel prefix="${prefix}/barrel_8" parent="${prefix}/wheel_s_link" dir="${-pi/2}"/>

    <!-- ===============  Transmission =============== -->
    <transmission name="${prefix}/wheel_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}/wheel_joint">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      </joint>
      <actuator name="${prefix}/wheel_motor">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>

    <!-- ===============  Gazebo =============== -->
    <gazebo reference="${prefix}/wheel_link">
      <mu1 value="0.8" />
      <mu2 value="0.8" />
      <material>Gazebo/Gray</material>
    </gazebo>
    <gazebo reference="${prefix}/motor_link">
      <mu1 value="0.8" />
      <mu2 value="0.8" />
      <material>Gazebo/Gray</material>
    </gazebo>
  </xacro:macro>
</robot>

