gun0:
  train:
    type: effort_controllers/JointPositionController
    joint: gun0/base2_joint
    pid: {p: 10, i: 0.1, d: 0, i_clamp: 0}
  elevation:
    type: effort_controllers/JointPositionController
    joint: gun0/gun_joint
    pid: {p: 10, i: 0.1, d: 0, i_clamp: 0}